import type { Campaign, PlatformSnapshot, UUID } from "./types";

export type PublishReadinessSection = "CAMPAIGN" | "PRODUCTS" | "DISPLAYS" | "STORES" | "ORDERING";
export interface PublishReadinessIssue { severity: "BLOCKING" | "WARNING"; section: PublishReadinessSection; code: string; message: string; storeId?: UUID; campaignDisplayId?: UUID; campaignDisplayAssignmentId?: UUID; displayAreaId?: UUID; productId?: UUID; }
export interface CampaignPublishReadiness { state: "READY" | "WARNING" | "BLOCKED"; issues: PublishReadinessIssue[]; }
export function evaluateCampaignPublishReadiness(campaign: Campaign | undefined, data: PlatformSnapshot | undefined): CampaignPublishReadiness {
  const issues: PublishReadinessIssue[] = []; const add = (severity: PublishReadinessIssue["severity"], section: PublishReadinessSection, code: string, message: string, extra = {}) => issues.push({ severity, section, code, message, ...extra });
  if (!campaign || !data) return { state: "BLOCKED", issues: [{ severity: "BLOCKING", section: "CAMPAIGN", code: "CAMPAIGN_MISSING", message: "Campaign data is unavailable." }] };
  if (!campaign.name || !campaign.owner || !campaign.startDate || !campaign.endDate || campaign.endDate < campaign.startDate) add("BLOCKING", "CAMPAIGN", "CAMPAIGN_METADATA", "Campaign name, owner, and valid dates are required.");
  if (!campaign.supplier) add("WARNING", "CAMPAIGN", "SUPPLIER_MISSING", "Supplier / partner is not specified.");
  const scopes = data.campaignStores.filter((item) => item.campaignId === campaign.id && item.included); if (!scopes.length) add("BLOCKING", "CAMPAIGN", "NO_STORES", "Include at least one participating store.");
  if (!campaign.products.length) add("BLOCKING", "PRODUCTS", "NO_PRODUCTS", "Add campaign products before release.");
  campaign.products.forEach((item) => { const product = data.products.find((candidate) => candidate.id === item.productId); if (!product || product.masterStatus === "unresolved") add("BLOCKING", "PRODUCTS", "PRODUCT_INVALID", "A campaign product has no valid Product Master identity.", { productId: item.productId }); else if (product.masterStatus === "pending" || !product.active) add("WARNING", "PRODUCTS", "PRODUCT_REVIEW", `${product.name} requires Product Master review.`, { productId: item.productId }); if (item.required && (item.merchandisingState ?? "UNASSIGNED") === "UNASSIGNED") add("BLOCKING", "DISPLAYS", "REQUIRED_UNASSIGNED", "A required product has no merchandising decision.", { productId: item.productId }); });
  const displays = data.campaignDisplays.filter((item) => item.campaignId === campaign.id); displays.forEach((display) => { const members = data.campaignDisplayProducts.filter((item) => item.campaignDisplayId === display.id); if (!members.length) add("WARNING", "DISPLAYS", "EMPTY_DISPLAY", `${display.name} has no products.`, { campaignDisplayId: display.id }); members.forEach((member) => { if (!campaign.products.some((product) => product.id === member.campaignProductId && product.productId === member.productId)) add("BLOCKING", "DISPLAYS", "DISPLAY_PRODUCT_INVALID", "A display product relationship is invalid.", { campaignDisplayId: display.id, productId: member.productId }); }); });
  scopes.forEach((scope) => displays.forEach((display) => { const assignment = data.campaignDisplayAssignments.find((item) => item.storeId === scope.storeId && item.campaignDisplayId === display.id); if (!assignment || assignment.status === "UNASSIGNED" || assignment.status === "SUGGESTED" || assignment.status === "NEEDS_REVIEW") add("BLOCKING", "STORES", "PLACEMENT_UNRESOLVED", `${display.name} needs a resolved placement.`, { storeId: scope.storeId, campaignDisplayId: display.id, campaignDisplayAssignmentId: assignment?.id }); else if (assignment.status === "EXCLUDED") add("WARNING", "STORES", "DISPLAY_EXCLUDED", `${display.name} is excluded from this store.`, { storeId: scope.storeId, campaignDisplayId: display.id }); else if (!assignment.displayAreaId) add("BLOCKING", "STORES", "AREA_MISSING", "Accepted placement has no physical display area.", { storeId: scope.storeId, campaignDisplayAssignmentId: assignment.id }); else if (assignment.compatibility === "review") add("WARNING", "STORES", "COMPATIBILITY_REVIEW", "Placement requires compatibility review.", { storeId: scope.storeId, campaignDisplayAssignmentId: assignment.id }); }));
  data.campaignDisplayAssignmentProducts.forEach((item) => { const assignment = data.campaignDisplayAssignments.find((candidate) => candidate.id === item.campaignDisplayAssignmentId); const displayProduct = data.campaignDisplayProducts.find((candidate) => candidate.id === item.campaignDisplayProductId); if (assignment?.campaignId !== campaign.id || assignment.status !== "ASSIGNED") return; if (displayProduct?.required && item.caseQuantity === undefined) add("BLOCKING", "ORDERING", "QUANTITY_MISSING", "A required display product has no final quantity.", { productId: item.productId, campaignDisplayAssignmentId: assignment.id }); if (!data.supplierProductOptions.some((option) => option.productId === item.productId)) add("WARNING", "ORDERING", "SUPPLIER_MISSING", "No supplier option is available for a planned product.", { productId: item.productId }); });
  return { state: issues.some((item) => item.severity === "BLOCKING") ? "BLOCKED" : issues.length ? "WARNING" : "READY", issues };
}
