import { expect } from "@playwright/test";
import { test } from "./localTest";

test("buyer creates, places, releases and reopens a durable manager pack without duplicating a release", async ({ page }, testInfo) => {
  test.setTimeout(45_000);
  await page.route("**/*.supabase.co/**", (route) => route.abort());
  const pageErrors: string[] = [];
  page.on("pageerror", (error) => pageErrors.push(error.message));
  page.on("dialog", (dialog) => dialog.accept());
  await page.goto("/campaigns/new");
  await page.getByLabel("Campaign name").fill("Buyer release acceptance");
  await page.getByLabel("Start date").fill("2027-10-01");
  await page.getByLabel("End date").fill("2027-10-31");
  await page.getByRole("button", { name: "Create campaign and continue" }).click();
  await page.getByRole("button", { name: "Add products", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Add products" });
  await dialog.getByLabel("Search Product Master").fill("MOCK-1001");
  await dialog.locator("label").filter({ hasText: "MOCK-1001" }).getByRole("checkbox").check();
  await dialog.getByRole("button", { name: "Add selected products" }).click();
  await page.getByRole("link", { name: "Continue to Displays" }).click();
  await page.getByRole("button", { name: "New display", exact: true }).click();
  await page.getByLabel("Display name", { exact: true }).fill("Beer feature");
  await page.getByRole("combobox", { name: "Display type", exact: true }).selectOption("flex");
  await page.getByLabel("Signage", { exact: true }).fill("Approved header and price tickets");
  await page.getByRole("button", { name: "Create display", exact: true }).click();
  await page.locator("label").filter({ hasText: "MOCK-1001" }).getByRole("checkbox").check();
  await page.getByLabel("Select display for products").selectOption({ label: "Beer feature" });
  await page.getByRole("button", { name: "Add / move selected" }).click();
  await expect(page.getByText("1 products", { exact: false }).first()).toBeVisible();
  await page.getByRole("button", { name: "Edit", exact: true }).last().click();
  await page.getByLabel("Minimum facings", { exact: true }).fill("3");
  await page.getByLabel("Campaign default quantity", { exact: false }).fill("5");
  await page.getByRole("button", { name: "Save product", exact: true }).click();
  await page.getByRole("button", { name: "Continue to Stores" }).click();
  await page.getByRole("checkbox", { name: /Crown Isle/ }).check();
  await page.getByLabel("Allocation filter").selectOption("all");
  await page.getByRole("button", { name: "Suggest placement", exact: true }).click();
  await page.getByRole("button", { name: "Store placement / quantities", exact: true }).click();
  const physical = page.getByRole("combobox", { name: "Physical display area", exact: true });
  const areaId = await physical.getByRole("option").filter({ hasText: /zone 1.*BR1/ }).getAttribute("value");
  expect(areaId).toBeTruthy();
  await physical.selectOption(areaId!);
  await page.getByRole("textbox", { name: /Display notes for/ }).fill("Store-specific approved instruction");
  await page.getByRole("button", { name: "Save display notes", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save display notes", exact: true })).toBeDisabled();
  await page.getByRole("link", { name: "Continue to Review", exact: true }).click();
  const reviewUrl = page.url();
  await page.getByRole("button", { name: "Finalize stores and publish", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "Release 1 saved for 1 store" })).toBeVisible();
  const releasedLink = page.getByRole("link", { name: "Release 1: Crown Isle pack", exact: true });
  const releaseUrl = await releasedLink.getAttribute("href");
  await releasedLink.click();
  await expect(page.getByText("Store-specific approved instruction", { exact: false })).toBeVisible();
  await expect(page.getByRole("row").filter({ hasText: "MOCK-1001" })).toContainText("Min. facings: 3");
  await expect(page.getByRole("row").filter({ hasText: "MOCK-1001" }).locator("td").nth(2)).toHaveText("5");
  await expect(page.getByRole("button", { name: "Print / Save letter-size PDF" })).toBeEnabled();
  await page.reload();
  await expect(page.getByText("Store-specific approved instruction", { exact: false })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("released-pack-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto(reviewUrl);
  await page.getByRole("button", { name: "Publish updated release", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "Release 1 saved for 1 store" })).toBeVisible();
  await expect(page.getByRole("link", { name: "Release 1: Crown Isle pack", exact: true })).toHaveAttribute("href", releaseUrl!);
  await page.goto(reviewUrl.replace(/\/review$/, "/assign"));
  await page.getByLabel("Allocation filter").selectOption("all");
  await page.getByRole("button", { name: "Store placement / quantities", exact: true }).click();
  await page.getByRole("textbox", { name: /Display notes for/ }).fill("Later unpublished instruction");
  await page.getByRole("button", { name: "Save display notes", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save display notes", exact: true })).toBeDisabled();
  await page.goto(releaseUrl!);
  await expect(page.getByText("Store-specific approved instruction", { exact: false })).toBeVisible();
  await expect(page.getByText("Later unpublished instruction", { exact: false })).toHaveCount(0);
  await page.getByRole("link", { name: "Campaign Review", exact: true }).click();
  await page.getByRole("button", { name: "Publish updated release", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "Release 2 saved for 1 store" })).toBeVisible();
  await page.goto(releaseUrl!);
  await expect(page.getByText("A newer release exists.", { exact: false })).toBeVisible();
  expect(pageErrors).toEqual([]);
});
