import { ArrowRight, Check, History, Lightbulb, TrendingUp, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import type { RecommendationStatus } from "../../domain/types";
import { Badge, Button, Card, DataState, EmptyState, Field, PageHeader, formatDate, humanize, inputClass } from "../../components/ui";
import { usePlatform } from "../../services/PlatformProvider";

export function PerformancePage() {
  const { data, loading, error, updateRecommendation, role } = usePlatform();
  const [areaFilter, setAreaFilter] = useState("all");
  const [campaignFilter, setCampaignFilter] = useState("all");
  const records = useMemo(() => data?.performance.filter((record) => (areaFilter === "all" || record.displayAreaId === areaFilter) && (campaignFilter === "all" || record.campaignId === campaignFilter)) ?? [], [areaFilter, campaignFilter, data]);
  const canAct = role !== "read_only";
  const action = (id: string, status: RecommendationStatus) => void updateRecommendation(id, status);
  return <DataState loading={loading} error={error}><PageHeader eyebrow="Measure & improve" title="Performance & Recommendations" description="Synthetic campaign measurements and transparent, rule-based recommendations. Results show association, not causality." />
    <Card><div className="grid gap-3 md:grid-cols-3"><Field label="Display area"><select className={inputClass} value={areaFilter} onChange={(e) => setAreaFilter(e.target.value)}><option value="all">All display areas</option>{data?.displayAreas.map((area) => <option value={area.id} key={area.id}>Crown Isle / {area.name}</option>)}</select></Field><Field label="Campaign"><select className={inputClass} value={campaignFilter} onChange={(e) => setCampaignFilter(e.target.value)}><option value="all">All campaigns</option>{data?.campaigns.map((campaign) => <option value={campaign.id} key={campaign.id}>{campaign.name}</option>)}</select></Field><Field label="Period"><select className={inputClass}><option>All measured periods</option></select></Field></div></Card>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Avg. sales lift", value: records.length ? `${(records.reduce((sum, item) => sum + item.salesLiftPercent, 0) / records.length).toFixed(1)}%` : "-" }, { label: "GM$ lift", value: `$${records.reduce((sum, item) => sum + item.grossMarginLift, 0).toLocaleString()}` }, { label: "Avg. compliance", value: records.length ? `${Math.round(records.reduce((sum, item) => sum + item.compliancePercent, 0) / records.length)}%` : "-" }, { label: "Open recommendations", value: data?.recommendations.filter((item) => item.status === "open").length ?? 0 }].map((item) => <Card key={item.label}><p className="text-sm text-text-muted">{item.label}</p><p className="mt-2 text-2xl font-semibold">{item.value}</p></Card>)}</div>
    <Card className="overflow-hidden p-0"><div className="border-b border-border px-4 py-3"><h2 className="font-semibold">Persistent display-area ranking</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-subtle/60 text-xs uppercase text-text-muted"><tr><th className="px-4 py-3">Display area</th><th className="px-4 py-3">Campaign</th><th className="px-4 py-3">Sales lift</th><th className="px-4 py-3">GM$ lift</th><th className="px-4 py-3">Unit lift</th><th className="px-4 py-3">Compliance</th><th className="px-4 py-3">OOS rate</th></tr></thead><tbody className="divide-y divide-border">{records.sort((a, b) => b.salesLiftPercent - a.salesLiftPercent).map((record) => { const area = data?.displayAreas.find((item) => item.id === record.displayAreaId); const campaign = data?.campaigns.find((item) => item.id === record.campaignId); return <tr key={record.id}><td className="px-4 py-3"><Link className="font-semibold text-primary" to={`/display-areas/${record.displayAreaId}`}>Crown Isle / {area?.name}</Link></td><td className="px-4 py-3">{campaign?.name}</td><td className="px-4 py-3 font-semibold text-success">{record.salesLiftPercent > 0 && "+"}{record.salesLiftPercent}%</td><td className="px-4 py-3">${record.grossMarginLift.toLocaleString()}</td><td className="px-4 py-3">{record.unitLiftPercent}%</td><td className="px-4 py-3">{record.compliancePercent}%</td><td className="px-4 py-3">{Math.round(record.outOfStockRate * 100)}%</td></tr>; })}</tbody></table></div></Card>
    <div><div className="mb-3 flex items-center gap-2"><Lightbulb className="h-5 w-5 text-warning" /><h2 className="font-semibold">Explainable recommendations</h2></div><div className="grid gap-3 lg:grid-cols-2">{data?.recommendations.map((recommendation) => { const area = data.displayAreas.find((item) => item.id === recommendation.displayAreaId); return <Card key={recommendation.id}><div className="flex items-start justify-between gap-3"><div><Badge tone={recommendation.status === "open" ? "warning" : "neutral"}>{humanize(recommendation.status)}</Badge><h3 className="mt-2 font-semibold">{recommendation.title}</h3><p className="mt-1 text-sm text-text-muted">Crown Isle / {area?.name}</p></div><TrendingUp className="h-5 w-5 text-primary" /></div><p className="mt-3 text-sm leading-6 text-text-secondary">{recommendation.rationale}</p><p className="mt-2 text-xs text-text-muted">Rule: {humanize(recommendation.rule)}. Advisory only.</p>{canAct && recommendation.status === "open" && <div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" onClick={() => action(recommendation.id, "accepted")}><Check className="h-4 w-4" />Accept</Button><Button variant="secondary" onClick={() => action(recommendation.id, "addressed")}>Already addressed</Button><Button variant="secondary" onClick={() => action(recommendation.id, "dismissed")}><X className="h-4 w-4" />Dismiss</Button></div>}</Card>; })}</div></div><p className="text-xs text-text-muted">All values on this screen are clearly synthetic development data and must not be interpreted as Cascadia business results.</p>
  </DataState>;
}

export function DisplayAreaProfilePage() {
  const { displayAreaId } = useParams();
  const { data, loading, error } = usePlatform();
  const area = data?.displayAreas.find((item) => item.id === displayAreaId);
  const store = data?.stores.find((item) => item.id === area?.storeId);
  const zone = data?.zones.find((item) => item.id === area?.zoneId);
  const fixture = data?.fixtures.find((item) => item.id === area?.fixtureId);
  const assignments = data?.assignments.filter((item) => item.displayAreaId === displayAreaId) ?? [];
  const currentAssignment = assignments.find((item) => data?.campaigns.find((campaign) => campaign.id === item.campaignId)?.status === "active");
  const currentCampaign = data?.campaigns.find((item) => item.id === currentAssignment?.campaignId);
  const history = data?.history.filter((item) => item.displayAreaId === displayAreaId) ?? [];
  const performance = data?.performance.filter((item) => item.displayAreaId === displayAreaId) ?? [];
  return <DataState loading={loading} error={error}>{!area ? <EmptyState title="Display area not found" message="The requested persistent display area is unavailable." /> : <><PageHeader eyebrow="Persistent display area" title={`${store?.name} / ${area.name}`} description={area.description} actions={<Link className="inline-flex min-h-9 items-center rounded-md border border-border bg-surface px-3 text-sm font-semibold" to={`/stores/${area.storeId}/floorplan?area=${area.id}`}>View on floorplan</Link>} />
    <div className="grid gap-4 xl:grid-cols-3"><Card><h2 className="font-semibold">Physical details</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-text-muted">Type</dt><dd className="font-medium">{humanize(area.type)}</dd></div><div><dt className="text-text-muted">Zone</dt><dd className="font-medium">{zone?.name}</dd></div><div><dt className="text-text-muted">Fixture</dt><dd className="font-medium">{fixture?.name}</dd></div><div><dt className="text-text-muted">Capacity</dt><dd className="font-medium">{area.capacity}</dd></div></dl></Card><Card className="xl:col-span-2"><h2 className="font-semibold">Currently running</h2>{currentCampaign ? <div className="mt-4"><div className="flex items-center gap-2"><h3 className="text-lg font-semibold">{currentCampaign.name}</h3><Badge tone="success">Active</Badge></div><p className="mt-2 text-sm text-text-secondary">{currentCampaign.description}</p><p className="mt-3 text-xs text-text-muted">{formatDate(currentCampaign.startDate)} to {formatDate(currentCampaign.endDate)}</p><Link className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-primary" to={`/campaigns/${currentCampaign.id}`}>Open campaign <ArrowRight className="h-4 w-4" /></Link></div> : <EmptyState title="Area available" message="No active campaign is assigned to this display area." />}</Card></div>
    <Card><div className="flex items-center gap-2"><History className="h-5 w-5 text-primary" /><h2 className="font-semibold">Campaign and execution history</h2></div>{history.length ? <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-text-muted"><tr><th className="pb-3">Campaign</th><th className="pb-3">Period</th><th className="pb-3">Execution</th><th className="pb-3">Compliance</th><th className="pb-3">Sales lift</th></tr></thead><tbody className="divide-y divide-border">{history.map((item) => { const campaign = data?.campaigns.find((entry) => entry.id === item.campaignId); const execution = data?.executions.find((entry) => entry.id === item.executionId); const review = data?.complianceReviews.find((entry) => entry.executionId === item.executionId); const result = data?.performance.find((entry) => entry.displayAreaId === area.id && entry.campaignId === campaign?.id); return <tr key={item.id}><td className="py-3 font-medium">{campaign?.name}</td><td className="py-3">{formatDate(item.startDate)} to {formatDate(item.endDate)}</td><td className="py-3"><Badge tone="success">{humanize(execution?.status ?? "unknown")}</Badge></td><td className="py-3">{review?.score ?? "-"}%</td><td className="py-3">{result ? `${result.salesLiftPercent > 0 ? "+" : ""}${result.salesLiftPercent}%` : "Limited data"}</td></tr>; })}</tbody></table></div> : <EmptyState title="Limited history" message="No completed campaign history is available for this area." />}</Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card><h2 className="font-semibold">Historical performance</h2>{performance.length ? <div className="mt-4 grid grid-cols-2 gap-3">{[{ label: "Avg. sales lift", value: `${(performance.reduce((sum, item) => sum + item.salesLiftPercent, 0) / performance.length).toFixed(1)}%` }, { label: "Avg. unit lift", value: `${(performance.reduce((sum, item) => sum + item.unitLiftPercent, 0) / performance.length).toFixed(1)}%` }, { label: "GM$ lift", value: `$${performance.reduce((sum, item) => sum + item.grossMarginLift, 0).toLocaleString()}` }, { label: "Measured campaigns", value: performance.length }].map((item) => <div key={item.label} className="rounded-md bg-subtle p-3"><p className="text-xs text-text-muted">{item.label}</p><p className="mt-1 text-xl font-semibold">{item.value}</p></div>)}</div> : <p className="mt-3 text-sm text-text-muted">Limited measured data.</p>}</Card><Card><h2 className="font-semibold">What appears to work here</h2><p className="mt-3 text-sm leading-6 text-text-secondary">Historically, this area appears to have supported promotional campaigns with visible feature products. The available sample is limited and may be worth considering alongside seasonality, inventory availability, and store execution before making allocation decisions.</p><p className="mt-3 text-xs text-text-muted">This is cautious interpretation of synthetic correlated data, not a causal claim.</p></Card></div>
  </>}</DataState>;
}

