import { ArrowLeft, Check, MapPin, MoveRight } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { getAssignmentCompatibility } from "../../domain/rules";
import { usePlatform } from "../../services/PlatformProvider";
import { Badge, Button, Card, DataState, EmptyState, Field, PageHeader, formatDate, humanize, inputClass } from "../../components/ui";

function useCampaign() {
  const { campaignId } = useParams();
  const platform = usePlatform();
  return { ...platform, campaign: platform.data?.campaigns.find((item) => item.id === campaignId) };
}

export function CampaignDetailPage() {
  const { campaign, data, loading, error, role } = useCampaign();
  const canEdit = role === "admin" || role === "merchandising";
  return <DataState loading={loading} error={error}>{!campaign ? <EmptyState title="Campaign not found" message="The requested campaign does not exist in this data adapter." /> : <>
    <PageHeader eyebrow="Campaign" title={campaign.name} description={campaign.description} actions={<>{canEdit && <Link className="inline-flex min-h-9 items-center rounded-md border border-border bg-surface px-3 text-sm font-semibold" to={`/campaigns/${campaign.id}/display`}>Design display</Link>}{canEdit && <Link className="inline-flex min-h-9 items-center rounded-md bg-primary px-3 text-sm font-semibold text-primary-foreground" to={`/campaigns/${campaign.id}/assign`}>Assign stores</Link>}</>} />
    <div className="grid gap-4 xl:grid-cols-3"><Card className="xl:col-span-2"><div className="flex items-center gap-2"><Badge tone={campaign.status === "active" ? "success" : campaign.status === "scheduled" ? "info" : "neutral"}>{campaign.status}</Badge><Badge>{campaign.type}</Badge></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-text-muted">Period</dt><dd className="mt-1 font-medium">{formatDate(campaign.startDate)} to {formatDate(campaign.endDate)}</dd></div><div><dt className="text-text-muted">Owner</dt><dd className="mt-1 font-medium">{campaign.owner}</dd></div><div><dt className="text-text-muted">Supplier / partner</dt><dd className="mt-1 font-medium">{campaign.supplier || "Not specified"}</dd></div><div><dt className="text-text-muted">Display type</dt><dd className="mt-1 font-medium">{humanize(campaign.requirement.displayType)}</dd></div></dl></Card><Card><h2 className="font-semibold">Execution guidance</h2><dl className="mt-3 space-y-3 text-sm"><div><dt className="text-text-muted">Signage</dt><dd>{campaign.requirement.signage || "None specified"}</dd></div><div><dt className="text-text-muted">Minimum space</dt><dd>{campaign.requirement.minimumSpace}</dd></div><div><dt className="text-text-muted">Approach</dt><dd>{campaign.requirement.prescriptive ? "Prescriptive" : "Guided local execution"}</dd></div></dl></Card></div>
    <Card className="overflow-hidden p-0"><div className="border-b border-border px-4 py-3"><h2 className="font-semibold">Campaign products</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-subtle/60 text-xs uppercase text-text-muted"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Requirement</th><th className="px-4 py-3">Minimum</th></tr></thead><tbody className="divide-y divide-border">{campaign.products.map((product) => <tr key={product.id}><td className="px-4 py-3"><p className="font-medium">{product.name}</p><p className="text-xs text-text-muted">{product.sku} · {product.category}</p></td><td className="px-4 py-3">{product.role}</td><td className="px-4 py-3"><Badge tone={product.required ? "error" : "info"}>{product.required ? "Required" : "Recommended"}</Badge></td><td className="px-4 py-3">{product.minimumQuantity} units · {product.minimumFacings} facings</td></tr>)}</tbody></table></div></Card>
    <Card><h2 className="font-semibold">Assignments</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{data?.assignments.filter((item) => item.campaignId === campaign.id).map((assignment) => { const store = data.stores.find((item) => item.id === assignment.storeId); const area = data.displayAreas.find((item) => item.id === assignment.displayAreaId); return <Link key={assignment.id} to={`/display-areas/${area?.id}`} className="flex items-center justify-between rounded-md border border-border p-3"><div><p className="font-medium">{store?.name} / {area?.name}</p><p className="text-xs text-text-muted">Effective {formatDate(assignment.effectiveDate)}</p></div><Badge tone="success">{humanize(assignment.compatibility)}</Badge></Link>; })}</div></Card>
  </>}</DataState>;
}

export function DisplayDesignerPage() {
  const { campaign, loading, error } = useCampaign();
  return <DataState loading={loading} error={error}>{!campaign ? <EmptyState title="Campaign not found" message="Unable to design this display." /> : <><PageHeader eyebrow="Design" title={`${campaign.name} display`} description="A lightweight guide for relative product prominence. This is not a pixel-perfect planogram." actions={<Link className="inline-flex min-h-9 items-center gap-2 rounded-md border border-border bg-surface px-3 text-sm font-semibold" to={`/campaigns/${campaign.id}`}><ArrowLeft className="h-4 w-4" />Campaign</Link>} />
    <div className="grid gap-4 xl:grid-cols-[1fr_340px]"><Card><div className="mx-auto max-w-3xl"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold">{humanize(campaign.requirement.displayType)} guide</p><Badge tone={campaign.requirement.prescriptive ? "error" : "info"}>{campaign.requirement.prescriptive ? "Prescriptive" : "Guidance"}</Badge></div><div className="grid min-h-[430px] grid-cols-2 gap-2 border-8 border-locked bg-subtle p-4 sm:grid-cols-3">{campaign.products.map((product, index) => <div key={product.id} className={`flex flex-col justify-between border-2 p-3 ${product.required ? "border-error bg-error/5" : "border-info bg-info/5"}`} style={{ minHeight: `${Math.max(100, 190 - index * 25)}px` }}><Badge tone={product.required ? "error" : "info"}>{product.required ? "Required" : "Recommended"}</Badge><div><p className="font-semibold">{product.name}</p><p className="mt-1 text-xs text-text-muted">{product.minimumFacings} minimum facing{product.minimumFacings === 1 ? "" : "s"}</p></div></div>)}</div><p className="mt-3 text-xs text-text-muted">Relative blocks communicate prominence only; store teams may adjust spacing unless marked prescriptive.</p></div></Card><div className="space-y-4"><Card><h2 className="font-semibold">Requirements</h2><dl className="mt-3 space-y-3 text-sm"><div><dt className="text-text-muted">Minimum space</dt><dd>{campaign.requirement.minimumSpace}</dd></div><div><dt className="text-text-muted">Signage</dt><dd>{campaign.requirement.signage}</dd></div><div><dt className="text-text-muted">Execution notes</dt><dd>{campaign.requirement.executionNotes}</dd></div></dl></Card><Card><h2 className="font-semibold">Placement order</h2><ol className="mt-3 space-y-2">{campaign.products.map((product, index) => <li key={product.id} className="flex items-center gap-2 text-sm"><span className="grid h-6 w-6 place-items-center rounded bg-subtle text-xs font-semibold">{index + 1}</span>{product.name}</li>)}</ol></Card></div></div>
  </>}</DataState>;
}

export function CampaignAssignmentPage() {
  const navigate = useNavigate();
  const { campaign, data, loading, error, assignCampaign } = useCampaign();
  const [areaId, setAreaId] = useState("");
  const [effectiveDate, setEffectiveDate] = useState("2026-09-01");
  const [notes, setNotes] = useState("");
  const [formError, setFormError] = useState<string>();
  const selectedArea = data?.displayAreas.find((item) => item.id === areaId);
  const compatibility = useMemo(() => campaign && selectedArea ? getAssignmentCompatibility(campaign, selectedArea) : undefined, [campaign, selectedArea]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!campaign || !selectedArea || !data?.stores[0]) return; try { await assignCampaign({ campaignId: campaign.id, storeId: selectedArea.storeId, displayAreaId: selectedArea.id, effectiveDate, notes }); navigate(`/stores/${selectedArea.storeId}/floorplan?area=${selectedArea.id}`); } catch (cause) { setFormError(cause instanceof Error ? cause.message : "Unable to assign campaign."); } };
  return <DataState loading={loading} error={error}>{!campaign ? <EmptyState title="Campaign not found" message="Unable to assign this campaign." /> : <form onSubmit={submit} className="space-y-6"><PageHeader eyebrow="Assign" title={`Assign ${campaign.name}`} description="Choose a store and persistent display area. Compatibility is based on the campaign display requirement." actions={<Button disabled={!areaId || compatibility === "incompatible"}><Check className="h-4 w-4" />Create assignment</Button>} />{formError && <div role="alert" className="rounded-md border border-error/30 bg-error/5 p-3 text-sm text-error">{formError}</div>}
    <div className="grid gap-4 xl:grid-cols-[1fr_360px]"><Card><h2 className="font-semibold">Crown Isle display areas</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{data?.displayAreas.map((area) => { const result = getAssignmentCompatibility(campaign, area); return <button type="button" key={area.id} onClick={() => setAreaId(area.id)} className={`text-left rounded-md border p-4 transition ${areaId === area.id ? "border-primary ring-2 ring-primary/15" : "border-border hover:border-primary/50"}`}><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{area.name}</p><p className="text-xs text-text-muted">{humanize(area.type)}</p></div><Badge tone={result === "compatible" ? "success" : result === "requires_review" ? "warning" : "error"}>{humanize(result)}</Badge></div><p className="mt-3 text-sm text-text-secondary">{area.description}</p></button>; })}</div></Card><div className="space-y-4"><Card><h2 className="font-semibold">Assignment details</h2><div className="mt-4 space-y-4"><Field label="Store"><input className={inputClass} value="Crown Isle" disabled /></Field><Field label="Effective date"><input type="date" className={inputClass} value={effectiveDate} onChange={(e) => setEffectiveDate(e.target.value)} /></Field><Field label="Store-specific notes"><textarea className={`${inputClass} min-h-24 py-2`} value={notes} onChange={(e) => setNotes(e.target.value)} /></Field></div></Card>{selectedArea && <Card><div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-primary" /><h2 className="font-semibold">{selectedArea.name}</h2></div><p className="mt-2 text-sm text-text-secondary">{selectedArea.capacity}</p><div className="mt-3 flex items-center gap-2 text-sm"><span>{humanize(campaign.requirement.displayType)}</span><MoveRight className="h-4 w-4 text-text-muted" /><span>{humanize(selectedArea.type)}</span></div></Card>}</div></div>
  </form>}</DataState>;
}
