import { Camera, CheckCircle2, MapPin, PackageX, Send } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Badge, Button, Card, DataState, EmptyState, Field, PageHeader, humanize, inputClass } from "../../components/ui";
import { usePlatform } from "../../services/PlatformProvider";

export function ExecutionPage() {
  const { executionId } = useParams();
  const navigate = useNavigate();
  const { data, loading, error, completeExecution, role } = usePlatform();
  const execution = data?.executions.find((item) => item.id === executionId);
  const assignment = data?.assignments.find((item) => item.id === execution?.assignmentId);
  const campaign = data?.campaigns.find((item) => item.id === assignment?.campaignId);
  const area = data?.displayAreas.find((item) => item.id === assignment?.displayAreaId);
  const [note, setNote] = useState(execution?.submission?.note ?? "");
  const [photoName, setPhotoName] = useState(execution?.submission?.photoName ?? "");
  const [unavailable, setUnavailable] = useState<string[]>(execution?.submission?.unavailableSkus ?? []);
  const [substitution, setSubstitution] = useState(execution?.submission?.substitutionRequested ?? false);
  const [formError, setFormError] = useState<string>();
  const canExecute = role !== "read_only";
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!execution) return; try { await completeExecution({ executionId: execution.id, note, photoName: photoName || undefined, unavailableSkus: unavailable, substitutionRequested: substitution }); navigate(`/compliance/${execution.id}`); } catch (cause) { setFormError(cause instanceof Error ? cause.message : "Unable to submit execution."); } };
  return <DataState loading={loading} error={error}>{!execution || !campaign || !area ? <EmptyState title="Execution not found" message="The requested task is unavailable." /> : <form onSubmit={submit} className="space-y-6"><PageHeader eyebrow="Execute" title={campaign.name} description={`${area.name} · ${area.description}`} actions={<><Link className="inline-flex min-h-9 items-center gap-2 rounded-md border border-border bg-surface px-3 text-sm font-semibold" to={`/stores/${area.storeId}/floorplan?area=${area.id}`}><MapPin className="h-4 w-4" />Locate</Link>{canExecute && <Button><Send className="h-4 w-4" />Submit completion</Button>}</>} />{formError && <div role="alert" className="rounded-md border border-error/30 bg-error/5 p-3 text-sm text-error">{formError}</div>}
    <div className="grid gap-4 xl:grid-cols-[1fr_380px]"><div className="space-y-4"><Card><div className="flex items-center justify-between"><h2 className="font-semibold">Product requirements</h2><Badge tone={execution.status === "completed" ? "success" : execution.status === "issue" ? "error" : "warning"}>{humanize(execution.status)}</Badge></div><div className="mt-4 divide-y divide-border">{campaign.products.map((product) => <div key={product.id} className="grid gap-3 py-3 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><div className="flex items-center gap-2"><p className="font-medium">{product.name}</p><Badge tone={product.required ? "error" : "info"}>{product.required ? "Required" : "Recommended"}</Badge></div><p className="mt-1 text-xs text-text-muted">{product.sku} · {product.role}</p></div><p className="text-sm">{product.minimumQuantity} units · {product.minimumFacings} facings</p><label className="flex items-center gap-2 text-sm text-text-secondary"><input type="checkbox" checked={unavailable.includes(product.sku)} onChange={(event) => setUnavailable((current) => event.target.checked ? [...current, product.sku] : current.filter((sku) => sku !== product.sku))} disabled={!canExecute} />Unavailable</label></div>)}</div></Card><Card><h2 className="font-semibold">Display guidance</h2><dl className="mt-3 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-text-muted">Signage</dt><dd className="mt-1 font-medium">{campaign.requirement.signage}</dd></div><div><dt className="text-text-muted">Minimum space</dt><dd className="mt-1 font-medium">{campaign.requirement.minimumSpace}</dd></div><div className="sm:col-span-2"><dt className="text-text-muted">Execution notes</dt><dd className="mt-1">{campaign.requirement.executionNotes}</dd></div></dl></Card></div>
      <div className="space-y-4"><Card><div className="flex items-center gap-2"><Camera className="h-4 w-4 text-primary" /><h2 className="font-semibold">Completion evidence</h2></div><div className="mt-4 space-y-4"><Field label="Completion photo" hint="Mock mode stores the file name only; no employee identity metadata is retained."><input type="file" accept="image/*" className="block w-full text-sm file:mr-3 file:rounded-md file:border-0 file:bg-subtle file:px-3 file:py-2 file:font-semibold" onChange={(event) => setPhotoName(event.target.files?.[0]?.name ?? "")} disabled={!canExecute} /></Field>{photoName && <div className="flex items-center gap-2 rounded-md bg-success/10 p-3 text-sm text-success"><CheckCircle2 className="h-4 w-4" />{photoName}</div>}<Field label="Completion note"><textarea className={`${inputClass} min-h-28 py-2`} value={note} onChange={(event) => setNote(event.target.value)} disabled={!canExecute} /></Field></div></Card>{unavailable.length > 0 && <Card><div className="flex gap-2 text-error"><PackageX className="h-5 w-5" /><div><h2 className="font-semibold">Product issue</h2><p className="mt-1 text-sm">{unavailable.join(", ")} marked unavailable.</p></div></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={substitution} onChange={(event) => setSubstitution(event.target.checked)} />Request an approved substitution</label></Card>}</div></div>
  </form>}</DataState>;
}

